baseURL = "https://subflow.se"
canonifyURLS = true
config = "config.toml"
disableKinds = ["taxonomy", "taxonomyTerm"]
disqusShortname = "zne"
googleAnalytics = ""
languageCode = "en-US"
tags = ["subflow", "web dev", "automation"]
theme = "osprey"
title = "Subflow | YES."
[Params]
ajaxFormspree = true
author = "Jonas Olsson"
cacheBustCSS = false
cacheBustJS = false
copyright = true
credit = true
customCSS = false
description = "Full-stack web developer and it-consultant based in Örebro, Sweden."
email = "jonas@subflow.se"
facebook = "zneee"
favicon = "favicon.ico"
github = "subflow"
googleTagManager = ""
highlightJS = true
linkedin = "jonas--olsson"
logoBig = "/images/sf-logo.png"
logoSmall = "/images/sf-logo-small.png"
opengraphImage = "/images/osprey.png"
tagline = "Webdev and custom workflows."
twitter = "lowtekse"
[[menu.main]]
name = "About"
url = "/#about"
weight = 1
[[menu.main]]
name = "Work"
url = "/#work"
weight = 2
[[menu.main]]
name = "Blog"
url = "/#blog"
weight = 3
[[menu.main]]
name = "Contact"
url = "/#contact"
weight = 4
[params]
ajaxFormspree = true
author = "Jonas Olsson"
cacheBustCSS = false
cacheBustJS = false
copyright = true
credit = false
customCSS = false
description = "Full-stack web developer and it-consultant based in Örebro, Sweden."
email = "jonas@subflow.se"
facebook = "zneee"
favicon = "favicon.ico"
github = "subflow"
googleTagManager = ""
highlightJS = true
linkedin = "jonas--olsson"
logoBig = "/images/sf-logo.png"
logoSmall = "/images/sf-logo-small.png"
opengraphImage = "/images/osprey.png"
tagline = "Webdev and custom workflows."
twitter = "lowtekse"
